### ISSUE TITLE
您能提供数据集吗？

### ISSUE THREAD

**Issue by jamsmp** [RemeaMiku/LXIntegratedNavigation#1]
非常感谢您所做的工作！能提供数据集、轨迹文件和IMU吗？

**Comment by RemeaMiku** [comment]
在 datas 目录下上传了遮蔽环境的 NovAtel 的 IMU 输出文件(.ASC)和 PosMind 解算结果文件(.pos)，采集自武汉大学信息学部友谊广场周围。
